language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - python manage.py test --noinput --settings ci_hackathon_july_2020.settings_test
