# Generated by Django 3.0.8 on 2020-07-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to='profile'),
        ),
    ]
