# Generated by Django 3.0.8 on 2020-07-04 21:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_auto_20200704_2101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserExtended',
        ),
    ]
