# Generated by Django 3.0.8 on 2020-07-07 02:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllStatusInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.PositiveIntegerField(blank=True, null=True,
                                                     validators=[django.core.validators.MinValueValidator(1),
                                                                 django.core.validators.MaxValueValidator(5)])),
                ('plans', models.TextField(max_length=250)),
                ('help', models.TextField(max_length=250)),
                ('user_id', models.PositiveIntegerField()),
                ('updated_date', models.DateTimeField()),
                ('family_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StatusInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.PositiveIntegerField(blank=True, null=True,
                                                     validators=[django.core.validators.MinValueValidator(1),
                                                                 django.core.validators.MaxValueValidator(5)])),
                ('plans', models.TextField(default='Nothing', max_length=250)),
                ('help', models.TextField(default='Nothing', max_length=250)),
                ('user_id', models.PositiveIntegerField()),
                ('family_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.PositiveIntegerField(blank=True,
                                                     choices=[(1, 'amazing'), (2, 'happy'), (3, 'good'), (4, 'sad'),
                                                              (5, 'terrible')], null=True,
                                                     validators=[django.core.validators.MinValueValidator(1),
                                                                 django.core.validators.MaxValueValidator(5)])),
                ('plans', models.TextField(default='Nothing', max_length=250)),
                ('help', models.TextField(default='Nothing', max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                               to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
