# Generated by Django 3.0.8 on 2020-07-07 02:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('status', '0002_auto_20200706_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='mood',
            field=models.PositiveIntegerField(blank=True,
                                              choices=[(1, 'amazing'), (2, 'happy'), (3, 'good'), (4, 'sad'),
                                                       (5, 'terrible')], null=True,
                                              validators=[django.core.validators.MinValueValidator(1),
                                                          django.core.validators.MaxValueValidator(5)]),
        ),
    ]
