# Generated by Django 3.0.8 on 2020-07-07 02:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('status', '0003_auto_20200707_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allstatusinput',
            name='help',
        ),
        migrations.RemoveField(
            model_name='allstatusinput',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='allstatusinput',
            name='plans',
        ),
        migrations.RemoveField(
            model_name='allstatusinput',
            name='updated_date',
        ),
    ]
